#!/usr/bin/env bash
# Open the Homebrew App Store pull request for a Cobalt release, in one step.
#
#   tools/submit-hbas.sh [x.y.z] [--dry-run]
#
# What it does, using the GitHub CLI as whoever is logged in (that is the point:
# the submission is made in the owner's name, on fortheusers' repository, and no
# agent does it):
#   1. checks the GitHub release v<version> exists with cobalt-<version>.wuhb,
#   2. downloads the `hbas-listing` artifact CI built on the tagged commit,
#   3. validates it with tools/check-hbas-listing.py,
#   4. forks fortheusers/wiiu-hbas-repo, adds or updates packages/Cobalt on a
#      branch, pushes it and opens the pull request with the details filled in.
# --dry-run stops before anything is pushed and leaves the folder to inspect.
# See docs/homebrew-app-store.md for what is and is not verified.
set -euo pipefail
cd "$(dirname "$0")/.."
root=$PWD

version=""
dry=0
for a in "$@"; do
  case $a in --dry-run) dry=1 ;; -*) echo "unknown flag $a" >&2; exit 2 ;; *) version=$a ;; esac
done
[ -n "$version" ] || version=$(sed -n 's/.*COBALT_VERSION "\(.*\)".*/\1/p' src/util/version.h)
tag=v$version
UPSTREAM=fortheusers/wiiu-hbas-repo
SELF=ewanc26/cobalt

command -v gh >/dev/null || { echo "needs the GitHub CLI (gh), logged in" >&2; exit 1; }

echo ">> release $tag"
assets=$(gh release view "$tag" -R "$SELF" --json assets --jq '.assets[].name') \
  || { echo "no GitHub release $tag; cut it with tools/release.sh first" >&2; exit 1; }
grep -qx "cobalt-$version.wuhb" <<<"$assets" \
  || { echo "release $tag has no cobalt-$version.wuhb" >&2; exit 1; }
grep -qx "update.json" <<<"$assets" || echo "warning: release $tag has no update.json (the in-app updater will not see it)" >&2

echo ">> listing artifact built by CI on $tag"
sha=$(gh api "repos/$SELF/commits/$tag" --jq .sha)
run=$(gh run list -R "$SELF" --workflow ci --commit "$sha" --status success --json databaseId --jq '.[0].databaseId')
[ -n "$run" ] && [ "$run" != null ] || { echo "no successful ci run on $sha" >&2; exit 1; }
rm -rf dist/hbas
gh run download "$run" -R "$SELF" -n hbas-listing -D dist/hbas
python3 tools/check-hbas-listing.py dist/hbas --expect-version "$version"

if [ $dry = 1 ]; then
  echo "dry run: the listing is in dist/hbas/packages/Cobalt; nothing was pushed"
  exit 0
fi

me=$(gh api user --jq .login)
echo ">> forking $UPSTREAM as $me"
gh repo fork "$UPSTREAM" --clone=false >/dev/null 2>&1 || true
base=$(gh repo view "$UPSTREAM" --json defaultBranchRef --jq .defaultBranchRef.name)
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
gh repo clone "$me/wiiu-hbas-repo" "$work/repo" -- --depth 1 --branch "$base" -q
cd "$work/repo"
# gh adds an `upstream` remote when it clones a fork, so only add it when it is missing.
git remote get-url upstream >/dev/null 2>&1 || git remote add upstream "https://github.com/$UPSTREAM.git"
git fetch -q --depth 1 upstream "$base" && git reset -q --hard "upstream/$base"

if [ -d packages/Cobalt ]; then verb="Update"; else verb="Add"; fi
branch="cobalt-$version"
git checkout -q -b "$branch"
rm -rf packages/Cobalt
mkdir -p packages
cp -r "$root/dist/hbas/packages/Cobalt" packages/Cobalt
git add packages/Cobalt
git commit -q -m "$verb Cobalt $version" -m "Cobalt is a Bluesky client for the Wii U, https://github.com/$SELF (AGPL-3.0). The package folder is generated by tools/make-hbas-listing.py from release $tag."
git push -q -u origin "$branch"

body="$verb Cobalt $version, a Bluesky client for the Wii U (Aroma, .wuhb).

- Source and releases: https://github.com/$SELF
- The update asset is the GitHub release asset https://github.com/$SELF/releases/download/$tag/cobalt-$version.wuhb, installed to /wiiu/apps/cobalt.wuhb.
- The folder (pkgbuild.json, icon, banner, screenshots) is generated by tools/make-hbas-listing.py in that repository. The screenshots are rendered on a PC from fixture data, not captured on a console.
- Cobalt checks its own GitHub releases for updates, only when the user asks, and never installs without confirmation.
- Verification so far: unit, end-to-end (against a mock PDS) and snapshot tests on a PC, and the .wuhb linking in CI. I have not run this build on a Wii U, so the first-run entropy seed and the updater are untested on hardware (https://github.com/$SELF/issues/24).

I'm the author and maintainer."
url=$(gh pr create --repo "$UPSTREAM" --base "$base" --head "$me:$branch" --title "$verb Cobalt $version" --body "$body")
echo ">> opened $url"
